repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0      # <--- updated from 23.9.1
    hooks:
      - id: black
        files: ^(src|tests)(/.*)?\.py$|^main\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(src|tests)(/.*)?\.py$|^main\.py$
